### ISSUE TITLE
Construcción de la ventana1 primera parte 

### ISSUE THREAD

**Issue by MaicolRua01** [MaicolRua01/clase9#1]
Construir la ventana ventana1 y hacer el formulario para ingresar la información del cliente

**Comment by SamuelCS45** [comment]
Saludos, voy a encargarme de esta funcionalidad

**Comment by MaicolRua01** [comment]
listo trabajo cumplido, por favor revisar el nuevo issue para hacer en ventana1.py el formulario de registro del usuario
