### ISSUE TITLE
Programar el botn para buscar las preguntas de recuperación de contraseña 

### ISSUE THREAD

**Issue by MaicolRua01** [MaicolRua01/clase9#6]
Validar que se ingrese el documento del usuario al cual se le va a buscar la contraseña 
Validar que el documento sea un dato tipo númerico 
Crear la clase usuario con sus 11 propiedades
Solo considerar un password
Buscar las preguntas para validar la contraseña

**Comment by michibonnet** [comment]
Me voy a encargar de este issue voy a desarrollarlo 
Pendiente de una suguerencia

**Comment by MaicolRua01** [comment]
Listo quedo pendiente de su primer push y pull request

**Comment by MaicolRua01** [comment]
se cierra este issues
